version: "3.9"
services:
  web:
    build: .
    command: bash -c "python /code/manage.py migrate && python /code/manage.py loaddata data.json && python /code/manage.py runserver 0.0.0.0:2530"
    volumes:
      - .:/code
    ports:
      - 2530:2530
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data: