# Generated by Django 4.0.8 on 2022-11-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ihacat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=100)),
                ('ModelName', models.CharField(max_length=100)),
                ('Weight', models.FloatField()),
                ('Categories', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='static/images')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
