# Generated by Django 4.0.8 on 2022-11-05 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ihacat',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='ihacat',
            old_name='Categories',
            new_name='categories',
        ),
        migrations.RenameField(
            model_name='ihacat',
            old_name='ModelName',
            new_name='modelName',
        ),
        migrations.RenameField(
            model_name='ihacat',
            old_name='Weight',
            new_name='weight',
        ),
    ]
