# Generated by Django 4.0.8 on 2022-11-05 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_brand_ihacat_brand_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ihacat',
            old_name='modelName',
            new_name='modelname',
        ),
    ]
